// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package injector

import (
	"github.com/ta93-ito/gomock_sample/handler"
	"github.com/ta93-ito/gomock_sample/infra"
	"github.com/ta93-ito/gomock_sample/usecase"
)

// Injectors from wire.go:

func NewUserHandler() *handler.UserHandler {
	user := infra.NewUserRepository()
	userUsecase := usecase.NewUserUsecase(user)
	userHandler := handler.NewUserHandler(userUsecase)
	return userHandler
}
