name: sample CI
on:
  push:
    branches:
      - master
  pull_request:
    branchs:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: set up Go 1.16.4
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.4

    - name: checkout latest code
      uses: actions/checkout@v1

    - name: get go dependencies
      run: go get -t -d ./...

    - name: run test
      run: go test ./...
